<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:eCH-0058="http://www.ech.ch/xmlns/eCH-0058/5"
  targetNamespace="http://www.ech.ch/xmlns/eCH-0058/5"
  elementFormDefault="qualified" version="5.0">
  <xs:simpleType name="businessReferenceIdType">
    <xs:restriction base="xs:token">
      <xs:minLength value="1"/>
      <xs:maxLength value="50"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="sendingApplicationType">
    <xs:sequence>
      <xs:element name="manufacturer">
        <xs:simpleType><xs:restriction base="xs:token">
          <xs:minLength value="1"/><xs:maxLength value="30"/>
        </xs:restriction></xs:simpleType>
      </xs:element>
      <xs:element name="product">
        <xs:simpleType><xs:restriction base="xs:token">
          <xs:minLength value="1"/><xs:maxLength value="30"/>
        </xs:restriction></xs:simpleType>
      </xs:element>
      <xs:element name="productVersion">
        <xs:simpleType><xs:restriction base="xs:token">
          <xs:minLength value="1"/><xs:maxLength value="10"/>
        </xs:restriction></xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>
